version: 1.0.{build}
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  project: AutoFake.sln
  verbosity: minimal
test_script:
- ;"%xunit20%\xunit.console.x86.exe" .\AutoFake.IntegrationTests\bin\%configuration%\AutoFake.IntegrationTests.dll -appveyor
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\AutoFake.UnitTests\bin\%configuration%\AutoFake.UnitTests.dll -noshadow -appveyor" -returntargetcode -filter:"+[AutoFake*]* -[AutoFake.UnitTests]*"  -hideskipped:All -output:.\AutoFake_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "AutoFake_coverage.xml"