<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AutoFake\AutoFake.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="xunit" Version="2.9.3" />
    </ItemGroup>

</Project>
